# Copyright (c) 2026 Omar Rao
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Commercial
# Available under the GNU Affero General Public License v3.0, or under a
# separate commercial license. See LICENSE and COMMERCIAL-LICENSE.md.

"""
Auto-fix PR generation.

After the AI advisor produces fix_suggestion patches, this module:
1. Creates a new branch securescope/fixes-{ts}
2. Applies the patches to the cloned repo
3. Opens a GitHub PR with a findings summary
"""
import logging
import os
import re
from pathlib import Path

logger = logging.getLogger(__name__)


def collect_fixable_findings(findings: list[dict]) -> list[dict]:
    """Return findings that have a non-empty fix_suggestion."""
    return [f for f in findings if f.get("fix_suggestion")]


def _strip_code_fences(text: str) -> str:
    """Remove ``` fences the LLM may wrap its answer in."""
    t = (text or "").strip()
    if t.startswith("```"):
        t = t.split("\n", 1)[1] if "\n" in t else ""
        if t.rstrip().endswith("```"):
            t = t.rstrip()[:-3]
    return t.rstrip("\n")


def _llm_code_fix(repo_path: str, finding: dict, call) -> bool:
    """Ask the LLM for a real code patch for the affected region and apply it.

    Returns True only when a plausible replacement was written. Conservative:
    empty / oversized / identical responses are rejected so a bad suggestion
    can't mangle the file.
    """
    file_rel = finding.get("file", "")
    if not file_rel or call is None:
        return False
    file_path = Path(repo_path) / file_rel
    if not file_path.exists():
        return False
    try:
        lines = file_path.read_text(encoding="utf-8", errors="replace").splitlines(keepends=True)
        start = max(0, int(finding.get("line_start", 1)) - 1)
        end = min(len(lines), int(finding.get("line_end", finding.get("line_start", 1))))
        if end <= start:
            end = min(len(lines), start + 1)
        region = "".join(lines[start:end])
        if not region.strip():
            return False
        system = (
            "You are a senior application-security engineer. You are given a code "
            "region containing a security finding. Return ONLY the corrected code "
            "for that exact region — no markdown fences, no commentary, no line "
            "numbers — preserving surrounding indentation and style. If you cannot "
            "fix it safely, return the region unchanged."
        )
        user_msg = (
            f"Rule: {finding.get('rule_id','')}\n"
            f"CWE: {finding.get('cwe','')}\n"
            f"Issue: {finding.get('message','')}\n\n"
            f"Code region to fix (lines {start+1}-{end} of {file_rel}):\n{region}"
        )
        fixed = _strip_code_fences(call(system, user_msg))
        if not fixed.strip():
            return False
        # Reject implausible rewrites (guards against the model going off-script).
        if len(fixed.splitlines()) > max(40, (end - start) * 4):
            return False
        if fixed.strip() == region.strip():
            return False
        if not fixed.endswith("\n"):
            fixed += "\n"
        new_lines = lines[:start] + [fixed] + lines[end:]
        file_path.write_text("".join(new_lines), encoding="utf-8")
        return True
    except Exception as exc:
        logger.warning("LLM code fix failed for %s: %s", file_rel, exc)
        return False


def _patch_file(repo_path: str, finding: dict) -> bool:
    """Apply fix_suggestion to the file as an inline comment. Returns True if patched."""
    file_rel = finding.get("file", "")
    fix = finding.get("fix_suggestion", "")
    if not file_rel or not fix:
        return False
    file_path = Path(repo_path) / file_rel
    if not file_path.exists():
        return False
    try:
        original = file_path.read_text(encoding="utf-8", errors="replace")
        # Write fix_suggestion as a comment block above the finding line
        line_no = finding.get("line_start", 1) - 1
        lines = original.splitlines(keepends=True)
        comment = f"# [SecureScope Fix] {finding.get('rule_id','')}: {fix}\n"
        lines.insert(max(0, line_no), comment)
        file_path.write_text("".join(lines), encoding="utf-8")
        return True
    except Exception as exc:
        logger.warning("Patch failed for %s: %s", file_rel, exc)
        return False


def create_fix_pr(
    repo_url: str,
    gh_token: str,
    workdir: str,
    findings: list[dict],
    ts: str,
    llm_provider: str = "",
    llm_api_key: str = "",
) -> str:
    """
    Create a branch with fixes and open a PR.

    When an LLM provider/key is supplied, each fixable finding gets a real
    code patch generated by the model (with a conservative sanity check);
    anything the model can't fix safely falls back to an inline fix comment.
    Returns the PR URL or empty string on failure.
    """
    import subprocess
    from github import Github

    fixable = collect_fixable_findings(findings)
    if not fixable:
        logger.info("No fixable findings — skipping auto-fix PR")
        return ""

    # Optional LLM client for real code patches (falls back to comments).
    call = None
    if llm_provider or llm_api_key or os.environ.get("ANTHROPIC_API_KEY"):
        try:
            from advisor import get_llm_client
            call = get_llm_client(llm_provider or "anthropic", llm_api_key)
        except Exception as exc:
            logger.info("auto-fix LLM unavailable, using comment mode: %s", exc)
            call = None

    branch = f"securescope/fixes-{ts}"

    try:
        # Configure git in the cloned workdir
        subprocess.run(["git", "config", "user.email", "securescope@noreply"], cwd=workdir, check=True)
        subprocess.run(["git", "config", "user.name", "SecureScope"], cwd=workdir, check=True)
        subprocess.run(["git", "checkout", "-b", branch], cwd=workdir, check=True)

        patched = 0
        code_fixes = 0
        for f in fixable:
            if call is not None and _llm_code_fix(workdir, f, call):
                patched += 1
                code_fixes += 1
            elif _patch_file(workdir, f):
                patched += 1
        logger.info("auto-fix: %d patched (%d real code fixes, %d comments)",
                    patched, code_fixes, patched - code_fixes)

        if patched == 0:
            return ""

        subprocess.run(["git", "add", "-A"], cwd=workdir, check=True)
        subprocess.run(
            ["git", "commit", "-m", f"[SecureScope] Add {patched} AI-generated fix suggestions"],
            cwd=workdir, check=True
        )

        # Push using token auth
        parsed = re.match(r"https://github\.com/([^/]+)/([^/]+?)(?:\.git)?$", repo_url)
        if not parsed:
            return ""
        owner, repo_name = parsed.group(1), parsed.group(2)
        push_url = f"https://x-access-token:{gh_token}@github.com/{owner}/{repo_name}.git"
        subprocess.run(["git", "push", push_url, branch], cwd=workdir, check=True)

        # Open PR via API
        gh = Github(gh_token)
        repo = gh.get_repo(f"{owner}/{repo_name}")
        default_branch = repo.default_branch
        pr_body = _build_pr_body(fixable, patched)
        pr = repo.create_pull(
            title=f"[SecureScope] AI-generated fix suggestions ({patched} findings)",
            body=pr_body,
            head=branch,
            base=default_branch,
        )
        logger.info("Fix PR opened: %s", pr.html_url)
        return pr.html_url

    except Exception as exc:
        logger.warning("Auto-fix PR failed: %s", exc)
        return ""


def _build_pr_body(findings: list[dict], patched: int) -> str:
    lines = [
        "## SecureScope — AI Fix Suggestions",
        "",
        f"This PR was automatically generated by [SecureScope](https://omarrao.github.io/secure-scope/).",
        f"**{patched} finding(s)** have inline fix suggestions added as comments above the affected lines.",
        "",
        "### Findings addressed",
        "",
        "| Severity | Rule | File | Line | Fix summary |",
        "|----------|------|------|------|-------------|",
    ]
    for f in findings[:20]:
        sev = f.get("severity", "")
        rule = f.get("rule_id", "").split(".")[-1]
        file_ = f.get("file", "")
        line = f.get("line_start", "")
        fix = (f.get("fix_suggestion") or "")[:80]
        lines.append(f"| {sev} | `{rule}` | `{file_}` | {line} | {fix} |")

    lines += [
        "",
        "> ⚠️ These are AI-generated fixes. Review each change carefully before merging.",
        "> Where the model produced a safe patch the code is edited directly; otherwise a",
        "> `[SecureScope Fix]` suggestion comment is inserted above the affected line.",
    ]
    return "\n".join(lines)
