"""
Auto-fix PR generation.

After the AI advisor produces fix_suggestion patches, this module:
1. Creates a new branch securescope/fixes-{ts}
2. Applies the patches to the cloned repo
3. Opens a GitHub PR with a findings summary
"""
import logging
import os
import re
from pathlib import Path

logger = logging.getLogger(__name__)


def collect_fixable_findings(findings: list[dict]) -> list[dict]:
    """Return findings that have a non-empty fix_suggestion."""
    return [f for f in findings if f.get("fix_suggestion")]


def _patch_file(repo_path: str, finding: dict) -> bool:
    """Apply fix_suggestion to the file. Returns True if patched."""
    file_rel = finding.get("file", "")
    fix = finding.get("fix_suggestion", "")
    if not file_rel or not fix:
        return False
    file_path = Path(repo_path) / file_rel
    if not file_path.exists():
        return False
    try:
        original = file_path.read_text(encoding="utf-8", errors="replace")
        # Write fix_suggestion as a comment block above the finding line
        line_no = finding.get("line_start", 1) - 1
        lines = original.splitlines(keepends=True)
        comment = f"# [SecureScope Fix] {finding.get('rule_id','')}: {fix}\n"
        lines.insert(max(0, line_no), comment)
        file_path.write_text("".join(lines), encoding="utf-8")
        return True
    except Exception as exc:
        logger.warning("Patch failed for %s: %s", file_rel, exc)
        return False


def create_fix_pr(
    repo_url: str,
    gh_token: str,
    workdir: str,
    findings: list[dict],
    ts: str,
) -> str:
    """
    Create a branch with fix comments and open a PR.
    Returns the PR URL or empty string on failure.
    """
    import subprocess
    from github import Github

    fixable = collect_fixable_findings(findings)
    if not fixable:
        logger.info("No fixable findings — skipping auto-fix PR")
        return ""

    branch = f"securescope/fixes-{ts}"

    try:
        # Configure git in the cloned workdir
        subprocess.run(["git", "config", "user.email", "securescope@noreply"], cwd=workdir, check=True)
        subprocess.run(["git", "config", "user.name", "SecureScope"], cwd=workdir, check=True)
        subprocess.run(["git", "checkout", "-b", branch], cwd=workdir, check=True)

        patched = 0
        for f in fixable:
            if _patch_file(workdir, f):
                patched += 1

        if patched == 0:
            return ""

        subprocess.run(["git", "add", "-A"], cwd=workdir, check=True)
        subprocess.run(
            ["git", "commit", "-m", f"[SecureScope] Add {patched} AI-generated fix suggestions"],
            cwd=workdir, check=True
        )

        # Push using token auth
        parsed = re.match(r"https://github\.com/([^/]+)/([^/]+?)(?:\.git)?$", repo_url)
        if not parsed:
            return ""
        owner, repo_name = parsed.group(1), parsed.group(2)
        push_url = f"https://x-access-token:{gh_token}@github.com/{owner}/{repo_name}.git"
        subprocess.run(["git", "push", push_url, branch], cwd=workdir, check=True)

        # Open PR via API
        gh = Github(gh_token)
        repo = gh.get_repo(f"{owner}/{repo_name}")
        default_branch = repo.default_branch
        pr_body = _build_pr_body(fixable, patched)
        pr = repo.create_pull(
            title=f"[SecureScope] AI-generated fix suggestions ({patched} findings)",
            body=pr_body,
            head=branch,
            base=default_branch,
        )
        logger.info("Fix PR opened: %s", pr.html_url)
        return pr.html_url

    except Exception as exc:
        logger.warning("Auto-fix PR failed: %s", exc)
        return ""


def _build_pr_body(findings: list[dict], patched: int) -> str:
    lines = [
        "## SecureScope — AI Fix Suggestions",
        "",
        f"This PR was automatically generated by [SecureScope](https://omarrao.github.io/secure-scope/).",
        f"**{patched} finding(s)** have inline fix suggestions added as comments above the affected lines.",
        "",
        "### Findings addressed",
        "",
        "| Severity | Rule | File | Line | Fix summary |",
        "|----------|------|------|------|-------------|",
    ]
    for f in findings[:20]:
        sev = f.get("severity", "")
        rule = f.get("rule_id", "").split(".")[-1]
        file_ = f.get("file", "")
        line = f.get("line_start", "")
        fix = (f.get("fix_suggestion") or "")[:80]
        lines.append(f"| {sev} | `{rule}` | `{file_}` | {line} | {fix} |")

    lines += [
        "",
        "> ⚠️ These are AI-generated suggestions. Review each one carefully before merging.",
        "> The fix comments are inserted inline — apply the actual code changes manually.",
    ]
    return "\n".join(lines)
